project:
    type: website
    title: "Inria Academy - Skrub like a pro"
    output-dir: _build
    pre-render:
       - "jupytext --to notebook ./content/exercises/*.py"
    render:
       - "**/*.qmd"
       - "!pixi.toml"
       - "!jupyterlite/**"
       - "!data/**"
       - "!content/chapters/helpers/**"

execute:
    freeze: auto    
website:
    title: "Inria Academy - Skrub like a pro"
    navbar:
      left:
          - text: "Home"
            href: index.html
          - text: "Book"
            href: book/index.html
          - text: "Slides"
            href: slides/index.html
          - text: "Exercises"
            menu:
              - text: "Exercise 1"
                href: exercises/exercise_01.html
              - text: "Exercise 2"
                href: exercises/exercise_02.html
              - text: "Exercise 3"
                href: exercises/exercise_03.html
              - text: "Exercise 4"
                href: exercises/exercise_04.html
format:
    html:
        theme: cosmo
        toc: true