project:
    type: website
    title: "Inria Academy - Skrub like a pro"
    output-dir: _build
    pre-render:
       - "jupytext --to notebook ./content/exercises/*.py"
       - "pixi run -e doc render-book"
       - "pixi run -e doc render-slides"
    render:
       - "**/*.qmd"
       - "**/*.ipynb"
       - "!pixi.toml"
       - "!jupyterlite/**"
       - "!data/**"
       - "!book/**"
       - "!slides/**"

website:
    title: "Inria Academy - Skrub like a pro"
    navbar:
      left:
          - text: "Home"
            href: /index.html
          - text: "Book"
            href: /book/index.html
          - text: "Slides"
            href: /slides/index.html
          - text: "JupyterLite"
            href: "/jupyterlite/lab/"
format:
    html:
        theme: [cosmo]
        toc: true
        toc-location: right

execute:
    freeze: auto