project:
  type: book
  title: "Inria Academy - Skrub like a pro (Book)"
  output-dir: ../_build/book

book:
  title: "Skrub like a pro - Book"
  author: "Riccardo Cappuzzo"
  page-navigation: true
  sidebar: false
  navbar:
    background: primary
    left:
      - text: "Home"
        href: ../index.html
      - text: "Book"
        href: index.html
      - text: "Slides"
        href: ../slides/index.html
      - text: "JupyterLite"
        href: ../jupyterlite/lab/
  chapters:
    - index.qmd
    - part: "Exploring and sanitizing data"
      chapters:
        - chapters/01_exploring_data.qmd
        - chapters/02_cleaning_data.qmd
        - chapters/quiz_01.qmd
    - part: "Transforming columns"
      chapters:
        - chapters/03_feat_eng_apply.qmd
        - chapters/04_selectors.qmd
        - chapters/quiz_02.qmd
    - part: "Feature Engineering with skrub"
      chapters:
        - chapters/05_feat_eng_numerical.qmd
        - chapters/06_feat_eng_datetimes.qmd
        - chapters/07_feat_eng_categorical.qmd
        - chapters/quiz_03.qmd
    - part: "Bringing it all together"
      chapters:
        - chapters/08_table_vectorizer.qmd
        - chapters/09_tabular_pipeline.qmd
        - chapters/quiz_04.qmd
    - chapters/10_conclusion.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
    code-fold: false
    code-tools: true

execute:
  freeze: auto
  keep-ipynb: true